apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  namespace: appsody-project
  name: appsody-hello-world
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: index.docker.io/odrodrig/tekton-test
            imagePullPolicy: Always
            ports:
            - containerPort: 9080
